### ISSUE TITLE
icon off partially working

### ISSUE THREAD

**Issue by sebest** [awolf78/KISS_OSD#11]
When I select icon off, the icon of the esc that are on the right and throttle are still visible.

**Comment by awolf78** [comment]
With "throttle" I guess you mean the amp meter. I noticed that recently too, will be fixed in next release. If you do not like the watt meter you can turn it off in the config tool.
Thanks for noticing the issue with the ESC icon, will also be fixed in next release.

**Comment by awolf78** [comment]
fixed in master
