### ISSUE TITLE
feature request: display gyro infos (X/Y angles)

### ISSUE THREAD

**Issue by sebest** [awolf78/KISS_OSD#14]
Would be nice to have the angle to know if we are level or not

**Comment by awolf78** [comment]
I think SAMUD's OSD version has a level indicator. I will not add this feature to my OSD since I have limited memory left and no one else but you has requested this feature.

**Comment by sebest** [comment]
To clarify, I'm asking for a level indicator like a bar or something moving.
just display a number being the angle in degrees, similar to what we have in the kiss gui next to the calibrate button.
