### ISSUE TITLE
No connection to FC

### ISSUE THREAD

**Issue by supernilz** [awolf78/KISS_OSD#16]
Hi,
I don't have connection to FC with the KISS_OSD but I do have a connection with the KISS_OSD_CONFIG tool, so RX and TX wires are correctly installed. 
What should I change or is this a bug?
Best Regards, Nils

**Comment by awolf78** [comment]
Does your KISS FC have V1.2 installed?
KISS OSD V2.3 requires KISS FC V.1.2.

**Comment by supernilz** [comment]
Thanks a lot! I didn't notice that I was still on V1.1.
