### ISSUE TITLE
no PID in menu 

### ISSUE THREAD

**Issue by bigrip** [awolf78/KISS_OSD#20]
hi
i use KISS_OSD V2.3.1 there is no tune menu like in the youtube video how can i turn this on?
if i disarm , the menu is always visible  is this normal  ?
i see on youtube yaw 3 sec to the right it opens the battery menu ,its not working for me.

**Comment by awolf78** [comment]
Please read wiki:
https://github.com/awolf78/KISS_OSD/wiki

Yaw 3 seconds to the left will open menu.

**Comment by bigrip** [comment]
i forget to flash the second hex file now it works .
