### ISSUE TITLE
Voltage wrong

### ISSUE THREAD

**Issue by maganzi** [awolf78/KISS_OSD#23]
Hello,

https://youtu.be/gSINJNPbjSk

voltage is wrong, if i throttle a bit, the voltage is rising up. 
If throttle 0% the voltage is 0.1V

Setup:
TBS Silk
Full KISS,
Lumenier PDB
TBS Unify Pro
Runcam RotorRiot Edition 
Piggy OSD Furious

**Comment by awolf78** [comment]
The video doesn't work, make sure you have it as "Unlisted" and not "Private" - otherwise I cannot see it.
Go in the KISS GUI, plug in a lipo and check the voltage in the upper right corner in the Advanced tab. What does it say there?

**Comment by maganzi** [comment]
![bildschirmfoto 2017-09-01 um 17 06 24](https://user-images.githubusercontent.com/10503526/29975780-ef916212-8f37-11e7-945b-15ccfd46e731.JPG)

i tried an older version of your OSD and in this version, the voltage is working perfectly fine.
The video will work now.
