### ISSUE TITLE
missing mah correction

### ISSUE THREAD

**Issue by olivier0253** [awolf78/KISS_OSD#24]
Hello,

I have 2.4 version and i would like to correct the mah consuption at screen.
As told in wiki, i go to BATTERY in KISS OSD but i don't find MAH CORRECTION.
Did i make a mistake? or this setup is available somewhere else?...

How can i do to correct the mah?

Thanks for your help

Olivier

**Comment by awolf78** [comment]
I've been a bit behind on releases. Just updated it, go to the release section.

**Comment by olivier0253** [comment]
Thank you for your job and your rapidity.
It works fine!
In the same way, how can i change TIMER setup (AUTO, RACE, RESET) with a 2.4 version and FC? I can't modify this setup in this version.
And i see MENU is disabled in RC4.3...
