### ISSUE TITLE
Issue with voltage correction (-)

### ISSUE THREAD

**Issue by olivier0253** [awolf78/KISS_OSD#26]
Hello,

I have (now) V2.4 RC4.3 and i meet issue when i want to make voltage correction.
When i apply positive correction, it seems to be good
However, when i apply negative one, it's run at first, but at next lipo, it's show me 42V at screen! (i run 4S)
So, i go to VOLTAGE CORRECTION and the value has move to 25V (approwimately, denpending of negative value i apply on previous lipo)
This issue occurs with kiss FC and CC.

Thanks for your job!

Olivier

**Comment by awolf78** [comment]
Ok, this has not been very well tested, thank you for reporting. I will look into this probably on Thursday.

**Comment by awolf78** [comment]
Try this one.

[KISS_OSD.ino.standard.zip](https://github.com/awolf78/KISS_OSD/files/1321453/KISS_OSD.ino.standard.zip)

**Comment by olivier0253** [comment]
Thanks
I'll test it asap, when i go back to home.
One question before install... How i should to do?
Like a basic firmware installation, with Xloader?

**Comment by awolf78** [comment]
Yes

**Comment by olivier0253** [comment]
I tried this file...
Installation seems to be good with Xloader, but when i plug in the lipo, i have no more OSD :-(

**Comment by awolf78** [comment]
What type of OSD hardware do you use?

**Comment by olivier0253** [comment]
i use piggy osd v2, with a 470uF capacitor

**Comment by awolf78** [comment]
[KISS_OSD.ino.eightanaloginputs.zip](https://github.com/awolf78/KISS_OSD/files/1344128/KISS_OSD.ino.eightanaloginputs.zip)
