### ISSUE TITLE
Question: What does the blinking red LED mean on the Steele PDB?

### ISSUE THREAD

**Issue by OnkelDisMaster** [awolf78/KISS_OSD#29]
I tried to search for a while now but nothing found.

**Comment by awolf78** [comment]
If it blinks in a regular, "heartbeat" rhythm: Everything is fine, the OSD main loop is running AND it is receiving data from the FC
If it blinks with a hiccup (little pause between blinks): OSD main loop is running but it is EITHER not receiving data from the FC OR it is waiting for user input to continue the last battery
It it does not blink at all: The OSD main loop does not run. This is not good and first remedy would be to flash the FW again. If that does not work or it still does not blink: not good. The led could be dead, but most likely the OSD chip is broken.
