### ISSUE TITLE
Add Issue to Troubleshooting section in wiki

### ISSUE THREAD

**Issue by OnkelDisMaster** [awolf78/KISS_OSD#30]
With the Steele PDB I was not able to flash the new firmware, neither on Mac or Windows. On Windows this issue was probably related to my updates being turned off. So I plugged the board in the windows machine and it recognized it as a CP2102 serial to USB adapter but it didn´t show the COM port in XLoader. So I did a quick search online and found the following drivers: 

https://www.pololu.com/docs/0J7 
(not sure if this is the right approach or just a lucky shot) 

Installing these, it worked right away. This also worked on OSX Sierra which was my main issue.
This might be useful for other people aswell.

Cheers 
ODM

**Comment by awolf78** [comment]
Done!

**Comment by ncloward** [comment]
I had the same problem since the port would never show up on OSX Sierra.  I installed the drivers and all was good.  Thanks @OnkelDisMaster.
