### ISSUE TITLE
No Connection To KISS FC - 1.3RC30

### ISSUE THREAD

**Issue by rogchap** [awolf78/KISS_OSD#33]
All the documentation states "1.2 and higher", but I'm getting the no connection to FC with latests KISS FW: 1.3RC30.

Are there planes to update to support 1.3?

FYI: I'm using the Steele PDB and trying to load the Config Tool on MacOSX (via the Other Platforms method).

**Comment by awolf78** [comment]
1.3 is fully supported (I'm running 1.3RC30 myself). Please check if none of the pins on your connectors are bent (KISS FC and Steele PDB).
