### ISSUE TITLE
voltage mah and amp draw stop working after first battery

### ISSUE THREAD

**Issue by loosepropfpv** [awolf78/KISS_OSD#34]
ok guys so after finish building the mr steele alien everything works great on the first flight voltage was working perfectly.(no crash) so to the second battery mah and amp start reading 0 and half way though the pack voltage was stuck on 15.6v so i came back put new battery in and now it only read the starting voltage can any one please help?? the voltage on my taranis is reading out fine

**Comment by awolf78** [comment]
What about the mAh on your Taranis? Is that 0 as well?

**Comment by loosepropfpv** [comment]
hi no is reading out correctly

**Comment by loosepropfpv** [comment]
and thank you for getting back to me so quick

**Comment by awolf78** [comment]
When the voltage is "stuck" in the OSD: can you Yaw to the left while disarmed for a few seconds to see if the menu still pops up?

**Comment by loosepropfpv** [comment]
yes the menu still popped up

**Comment by awolf78** [comment]
Very strange. Since your Taranis is reporting mAh correctly I am assuming the ESC telemetry is still working. And since you can get in the menu in the OSD, the communication between FC and OSD works properly. Somehow the FC is not reporting the ESC telemetry correctly for some reason - I would try flashing the FC first and then the PDB.

**Comment by loosepropfpv** [comment]
hi there i just accidentally fix the problem. when i was in the telementry screen i press the wrong button and it delete all the data and when i press all the discover new sensor all my bam all osd is now reading correctly!!! thank you for your time!!! but is all fix!!

**Comment by loosepropfpv** [comment]
i will leave this thread open till test flight tomorrow

**Comment by loosepropfpv** [comment]
thank you for your work in the fpv community and hope you carry on on what you doing!!!!

**Comment by awolf78** [comment]
So you fixed it by doing a rediscover on your Taranis?

**Comment by loosepropfpv** [comment]
yes by accident!!!!

**Comment by awolf78** [comment]
Interesting, who would have though that has anything to do with that...

**Comment by loosepropfpv** [comment]
maybe it sorted itself out????

**Comment by loosepropfpv** [comment]
Hi again so now I have the same issue however this time sometime it works and sometime it don’t for example in mid flight it will work for 30sec then it will freeze all amp mah and voltage stay the same and then it will work again

**Comment by awolf78** [comment]
Try flashing your KISS FC again. I don't think it is the PDB since it does not report any connection loss from the FC. The FC just keeps reporting the same telemetry data intermittently, so something is wrong on the FC.

**Comment by loosepropfpv** [comment]
Perfect my friend thank you

**Comment by loosepropfpv** [comment]
Hi again I have now reflash the fc and osd work for 4sec now is saying no connection to fc

**Comment by loosepropfpv** [comment]
Restart it now and gain osd

**Comment by awolf78** [comment]
So it is working now?

**Comment by loosepropfpv** [comment]
Hi again let start this again I found now that the telematary is not working right on my taranis aswell the freezes aswell so I don’t think is the osd
