### ISSUE TITLE
Strange Icon

### ISSUE THREAD

**Issue by danricho** [awolf78/KISS_OSD#39]
![kissosd_snap](https://user-images.githubusercontent.com/2055561/37194123-760bc188-23b8-11e8-9f6c-7a9565853f65.png)

I'm encountering a strange issue where the minimOSD is adding a strange character as shown in the attached image.

It happens after the font has been loaded and persistents on both the config and standard hex firmware. It doesn't change position or disappear when the menus are accessed either.

I've loaded multiple times using both XLoader and the firmware tool on mwosd.
I've also tried clearing the eeprom via the mwosd tool.

This is all regarding KISS_OSD V2.5

Any ideas?

Thanks for your great work!
Dan.

**Comment by awolf78** [comment]
The character on the top right is the Wattmeter - you can turn that off in the config tool under DISPLAY->WATTMETER.
The character in the middle of the screen should not be there at all. It is part of the alternative Wattmeter (beermug). I am suspecting that the font memory and/or your OSD chip on your micro minimosd might be defective.
Try turning the Wattmeter off first - if that does not help you will have to get new micro minimOSD. At least those are not very expensive.

**Comment by danricho** [comment]
Understood. I was mainly talking about the centre icon.

I have ordered a new minimosd and will report back.

Thanks for the assist.
