### ISSUE TITLE
Having Compile Errors

### ISSUE THREAD

**Issue by fjbravo** [awolf78/KISS_OSD#4]
Getting some compile error when uploading the fw to the minim osd
I added the both libs to arduino:  MAX7475 and SerialPort and still getting errors.
here is the output of the build:
http://pastebin.com/VdhEZzPp

**Comment by awolf78** [comment]
Looks like the libraries are now double. You should not have to include the libs to arduino for it to compile correctly. Not sure what you did, but try undoing it.
Also: Are you using Arduino 1.0.5-r2?
