### ISSUE TITLE
Support Betaflight's canvas mode (CMS_DisplayPort)

### ISSUE THREAD

**Issue by tcalvert** [awolf78/KISS_OSD#40]
Betaflight 3.1+ has a MSP_DisplayPort command which lets it show its own OSD runes via an external device.

I know this software already supports most of the betaflight features, but I think it would be really cool to have this nonetheless!

FWIW, MW_OSD has support for this via the `#define CANVAS_SUPPORT`.

**Comment by awolf78** [comment]
You already made the point, this is just a simple remote control for the BF OSD. There is no need for my FW to support it, because MWOSD already supports this. If you want to use canvas mode, please use MWOSD.
