### ISSUE TITLE
10sec. delay of OSD values after arming/disarming

### ISSUE THREAD

**Issue by stephanpitzl** [awolf78/KISS_OSD#41]
Hi there,

I got a problem with the Kiss OSD of my Kiss FC V2 + Mr. Steele PDB + TBS Unify Pro V2!

In my OSD I've displayed the Volts, Amps, mAmps, Throttle % and a Timer.

If I arm/disarm the Quad the OSD shows "armed" and "disarmed" instantly, just like Throttle % and the Timer working fine with no delay!

But the Volts, Amps and mAmps have a delay of about 10 seconds till they start counting and measuring correctly...

I got the newest firmware on the FC V2 and the Steele PDB and i flashed the FC first, then the PDB via the GUI and did this two times but nothing fixed the problem yet...

I also flashed a older Firmware on the PDB but the same problem.

Please help me!

**Comment by awolf78** [comment]
I have responded in RC Groups, so I am closing this one
