### ISSUE TITLE
Blheli32__ telemetry not working..

### ISSUE THREAD

**Issue by bfasty** [awolf78/KISS_OSD#45]
I have an aikon ak32 and I was thinking it would work with my kiss FC but it's not.... Does blheli32 work with your OSD?  Any other thoughts?

**Comment by awolf78** [comment]
Has nothing to do with my OSD. The FC receives telemetry from the (Blheli32) ESCs. Looks like that communication is not working. Most likely a short in one of the telemetry wires. I would disconnect them one by one and then check with the KISS GUI if you receive telemetry.
