### ISSUE TITLE
GPS Arrow with mr Steele pdb

### ISSUE THREAD

**Issue by mattyfpv** [awolf78/KISS_OSD#48]
Its possible to have the GPS function with mr Steele pdb?

**Comment by awolf78** [comment]
No more program space available, sorry. I have been working with ImpulseRC over the past couple of months on a new PDB which has GPS support (and much more). Should hit the stores in less than a month.

**Comment by mattyfpv** [comment]
Awesome bro!! Thanks

Il lun 28 mag 2018, 23:15 awolf78 <notifications@github.com> ha scritto:
