### ISSUE TITLE
Setting VTX Power via OSD (Wolf PDB with KISS FC v1)

### ISSUE THREAD

**Issue by Oberlurch3000** [awolf78/KISS_OSD#56]
Hello,

I've got a strange problem with setting my vtx power via OSD.
So first:
My TBS Unify Pro is soldered to the VTX Smart Audio Pad and the Audio in Pad on the PDB.
All connections between the FC an the PDB are the two plugs PORT 1 and 2.
My KISS FW ist RC36i and my PDB is up to date too.

Now if I go to the section where I can set VTX Power, Channel and so on I get a "bug" at the power, where I can't set it higher. It seems that roll right doesn't work.
In the whole OSD everthing works fine, just at this point I gets stuck.

After some work on the drone I am able to set the power up to 200mW but not higher.
Downwards from 600mW or 800mW is alway possible... but setting it higher again not.

Therefore I have to use the KISS GUI and I can set it to 600mW or higher again.

Any advice would be great!

**Comment by awolf78** [comment]
Did you unlock your VTX?

**Comment by Oberlurch3000** [comment]
Yes I did. I can set it up to 800mW with KISS GUI but not via OSD.
The Communication between FC and PDB should work out of the box right?
So if I change settings in the FC the PDB will recognize it and change it too.
I ask because it is possible to make changes on both GUI (FC and PDB).

**Comment by awolf78** [comment]
What is your VTX max power set at?

**Comment by Oberlurch3000** [comment]
Wow, just got it. Tried to make a short clip to show you and saw that there are advanced settings with a max power value... that solved my problem.
Thank you very much!

**Comment by awolf78** [comment]
Great!
