### ISSUE TITLE
Mr. Steele pdb props all over screen

### ISSUE THREAD

**Issue by Skitzizmo** [awolf78/KISS_OSD#57]
Hi Alex,
I have the problem where sometimes as I'm flying without warning prop icons fill the screen.
It goes away after I recycle the battery but I would like to know the cause of this.
My setup.
Mr Steele pdb
Kiss V2
Kiss 24amp ESC
Runcam micro eagle
Tramp HV

Thanks,
    Scott

**Comment by awolf78** [comment]
Most probably a tiny crack in the board from a crash.

**Comment by Skitzizmo** [comment]
Any way to fix it/ repair or its straight up replacement job

**Comment by awolf78** [comment]
Contact ImpulseRC, but most likely a replacement.
