### ISSUE TITLE
mr steele pdb 

### ISSUE THREAD

**Issue by peterbakerwatkins** [awolf78/KISS_OSD#59]
I have set up the mr steele pdb and gotten to the set up menu but can not scroll through the menu to set anything up...I am trying to use a crossfire nano rx...everything seems to be working properly except the scroll arrow...can not enter any items on the menu...thanks for your help!!

**Comment by awolf78** [comment]
Please double check if your endpoints in the KISS GUI are ok. And if the RX is correctly configured on the FC.

**Comment by peterbakerwatkins** [comment]
Ok... I thought I had to configure the pdb first... I did verify the fc but then reloaded the pdb config... thank you for your prompt response... really enjoy the kiss products... I’m sold!:)
